name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: ./MyLibrary
        run: pwd
      - name: Run tests
        run: swift test