name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run local server
        working-directory: ./MyLibrary
        run: |
        pip install Flask
        python app.py
      - name: Build
        working-directory: ./MyLibrary
        run: swift build
      - name: Run tests
        working-directory: ./MyLibrary
        run: swift test